services:
  - type: web
    name: tontine-backend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
